version: '3.8'
services:
  frontend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - backend
  backend:
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - LDAP_URL=${LDAP_URL}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
